TARGET = asteroids
OBJS = main.o j2me_runtime.o j2me_gfx.o j2me_font.o j2me_input.o

EXTRA_TARGETS = EBOOT.PBP
PSP_EBOOT_TITLE = asteroids

PSPSDK = $(shell psp-config --pspsdk-path)
include $(PSPSDK)/lib/build.mak
