TARGET = funtetris
OBJS = main.o j2me_runtime.o j2me_gfx.o j2me_font.o j2me_input.o j2me_image.o

EXTRA_TARGETS = EBOOT.PBP
PSP_EBOOT_TITLE = funtetris

PSPSDK = $(shell psp-config --pspsdk-path)
include $(PSPSDK)/lib/build.mak
